//dummy data
module.exports = {
    users: [
        { name: 'Sun', email: 'a@a.a', password: '$2a$10$ZFE0uWh/CH1dYCRkXq/PV.SRJRLsqkOrgcZHTLEb14XdVD4NKYZi6', following: ['Moon', 'Meow'], followers: ['Moon', 'Meow'] },
        { name: 'Moon', email: 'e@e.e', password: '$2a$10$OoGHxLd12VczgLXIQMQNZuw2ab3zZYM5QhObXE2dWWXJbqgByizAa', following: ['Meow', 'Lulu', 'Luke', 'Sun'], followers: ['Sun'] },
        { name: 'Lulu', email: 'i@i.i', password: '$2a$10$xy3087zPzW/HX9g/w.nRiuGtwgZqxhxp3vfNrzIogvppkEwg.ehXG', following: ['Meow'], followers: ['Moon'] },
        { name: 'Luke', email: 'o@o.o', password: '$2a$10$z03CVuc2aiiKUD7DhWmqxuO1vJwQer2XvcEJANJFPJLvjUOWgDSXq', following: ['Meow'], followers: ['Moon'] },
        { name: 'Meow', email: 'u@u.u', password: '$2a$10$mB8GuFL8KhBNHkyLXX0DlemjCHQ0fTw9uIJropeuuBJ1fTwpv0Q6e', following: ['Sun'], followers: ['Sun', 'Moon', 'Lulu', 'Luke'] }
    ],
    posts: [
        { title: 'Dog', author: 'Meow', body: "The dog or domestic dog is a domesticated descendant of the wolf. The dog is derived from an ancient, extinct wolf, and the modern wolf is the dog's nearest living relative. The dog was the first species to be domesticated, by hunter-gatherers over 15,000 years ago, before the development of agriculture. Due to their long association with humans, dogs have expanded to a large number of domestic individuals and gained the ability to thrive on a starch-rich diet that would be inadequate for other canids.\r\n\r\nThe dog has been selectively bred over millennia for various behaviors, sensory capabilities, and physical attributes. Dog breeds vary widely in shape, size, and color. They perform many roles for humans, such as hunting, herding, pulling loads, protection, assisting police and the military, companionship, therapy, and aiding disabled people. Over the millennia, dogs became uniquely adapted to human behavior, and the human-canine bond has been a topic of frequent study.(Source: Wikipedia)", date: '23/06/2022', time: '10:10', likedBy: ['Sun', 'Moon', 'Lulu'] },
        { title: 'Hamster', author: 'Meow', body: "Hamsters are rodents belonging to the subfamily Cricetinae, which contains 19 species classified in seven genera. They have become established as popular small pets. The best-known species of hamster is the golden or Syrian hamster (Mesocricetus auratus), which is the type most commonly kept as pets. Other hamster species commonly kept as pets are the three species of dwarf hamster, Campbell's dwarf hamster (Phodopus campbelli), the winter white dwarf hamster (Phodopus sungorus) and the Roborovski hamster (Phodopus roborovskii).\r\n\r\nHamsters are more crepuscular than nocturnal and, in the wild, remain underground during the day to avoid being caught by predators. They feed primarily on seeds, fruits, and vegetation, and will occasionally eat burrowing insects. Physically, they are stout-bodied with distinguishing features that include elongated cheek pouches extending to their shoulders, which they use to carry food back to their burrows, as well as a short tail and fur-covered feet.(Source: Wikipedia)", date: '01/02/2022', time: '12:10', likedBy: ['Sun', 'Moon'] },
        { title: 'Zebra', author: 'Meow', body: "Zebras are African equines with distinctive black-and-white striped coats. There are three living species: the Grévy's zebra (Equus grevyi), plains zebra (E. quagga), and the mountain zebra (E. zebra). Zebras share the genus Equus with horses and asses, the three groups being the only living members of the family Equidae. Zebra stripes come in different patterns, unique to each individual. Several theories have been proposed for the function of these stripes, with most evidence supporting them as a deterrent for biting flies. Zebras inhabit eastern and southern Africa and can be found in a variety of habitats such as savannahs, grasslands, woodlands, shrublands, and mountainous areas.\r\n\r\nZebras are primarily grazers and can subsist on lower-quality vegetation. They are preyed on mainly by lions and typically flee when threatened but also bite and kick. Zebra species differ in social behaviour, with plains and mountain zebra living in stable harems consisting of an adult male or stallion, several adult females or mares, and their young or foals; while Grévy's zebra live alone or in loosely associated herds. In harem-holding species, adult females mate only with their harem stallion, while male Grévy's zebras establish territories which attract females and the species is promiscuous. Zebras communicate with various vocalisations, body postures and facial expressions. Social grooming strengthens social bonds in plains and mountain zebras.(Source: Wikipedia)", date: '01/03/2022', time: '10:10' },
        { title: 'Java', author: 'Sun', body: "Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible. It is a general-purpose programming language intended to let programmers write once, run anywhere (WORA), meaning that compiled Java code can run on all platforms that support Java without the need to recompile. Java applications are typically compiled to bytecode that can run on any Java virtual machine (JVM) regardless of the underlying computer architecture. The syntax of Java is similar to C and C++, but has fewer low-level facilities than either of them. The Java runtime provides dynamic capabilities (such as reflection and runtime code modification) that are typically not available in traditional compiled languages. As of 2019, Java was one of the most popular programming languages in use according to GitHub, particularly for client–server web applications, with a reported 9 million developers.(Source: Wikipedia)", date: '23/06/2022', date: '23/04/2022', time: '10:10', likedBy: ['Meow', 'Luke', 'Lulu'] },
        { title: 'C++', author: 'Sun', body: "C++ is a general-purpose programming language created by Danish computer scientist Bjarne Stroustrup as an extension of the C programming language, or \"C with Classes\". The language has expanded significantly over time, and modern C++ now has object-oriented, generic, and functional features in addition to facilities for low-level memory manipulation. It is almost always implemented as a compiled language, and many vendors provide C++ compilers, including the Free Software Foundation, LLVM, Microsoft, Intel, Embarcadero, Oracle, and IBM, so it is available on many platforms.\r\n\r\nC++ was designed with systems programming and embedded, resource-constrained software and large systems in mind, with performance, efficiency, and flexibility of use as its design highlights. C++ has also been found useful in many other contexts, with key strengths being software infrastructure and resource-constrained applications, including desktop applications, video games, servers (e.g. e-commerce, web search, or databases), and performance-critical applications (e.g. telephone switches or space probes).(Source: Wikipedia)", date: '23/03/2022', time: '15:10', likedBy: ['Meow', 'Luke', 'Lulu'] },
        { title: 'First Post', author: 'Lulu', body: "First post by Lulu :)", date: '23/06/2022', time: '08:00' },
        { title: 'The Moon', author: 'Moon', body: "The Moon is Earth's only natural satellite. Together with Earth it forms the Earth–Moon satellite system. It is about one-quarter of Earth in diameter (comparable to the width of Australia). In the Solar System it is the fifth largest satellite, larger than any of the known dwarf planets and the largest (and most massive) satellite of a planet relative to the planet. The Moon is a planetary-mass object that formed a differentiated rocky body, making it a satellite planet under the geophysical definitions of the term. It lacks any significant atmosphere, hydrosphere, or magnetic field. Its surface gravity is about one-sixth of Earth's (0.1654 g). Jupiter's moon Io is the only satellite in the Solar System known to have a higher surface gravity and density.", date: '23/06/2022', time: '10:10' }
    ]
}

//User - Password (usernames are case-sensitive!)
//Sun - a
//Moon - e
//Lulu - i
//Luke - o
//Meow - u
